"""Pydantic schemas package."""
from .peering import (
    BGPPeeringBase,
    BGPPeeringCreate,
    BGPPeeringResponse,
    BGPPeeringUpdate,
    PeeringStatus,
    AddressFamily as AddressFamilyEnum,
)
from .entities import (
    TagBase,
    TagCreate,
    TagResponse,
    TagUpdate,
    AutonomousSystemBase,
    AutonomousSystemCreate,
    AutonomousSystemResponse,
    AutonomousSystemUpdate,
    PeerGroupBase,
    PeerGroupCreate,
    PeerGroupResponse,
    PeerGroupUpdate,
    PeerEndpointBase,
    PeerEndpointCreate,
    PeerEndpointResponse,
    PeerEndpointUpdate,
    RoutingPolicyBase,
    RoutingPolicyCreate,
    RoutingPolicyResponse,
    RoutingPolicyUpdate,
    AddressFamilyBase,
    AddressFamilyCreate,
    AddressFamilyResponse,
    AddressFamilyUpdate,
)

__all__ = [
    # Peering schemas
    "BGPPeeringBase",
    "BGPPeeringCreate",
    "BGPPeeringResponse",
    "BGPPeeringUpdate",
    "PeeringStatus",
    "AddressFamilyEnum",
    # Entity schemas
    "TagBase",
    "TagCreate",
    "TagResponse",
    "TagUpdate",
    "AutonomousSystemBase",
    "AutonomousSystemCreate",
    "AutonomousSystemResponse",
    "AutonomousSystemUpdate",
    "PeerGroupBase",
    "PeerGroupCreate",
    "PeerGroupResponse",
    "PeerGroupUpdate",
    "PeerEndpointBase",
    "PeerEndpointCreate",
    "PeerEndpointResponse",
    "PeerEndpointUpdate",
    "RoutingPolicyBase",
    "RoutingPolicyCreate",
    "RoutingPolicyResponse",
    "RoutingPolicyUpdate",
    "AddressFamilyBase",
    "AddressFamilyCreate",
    "AddressFamilyResponse",
    "AddressFamilyUpdate",
]
